### ISSUE TITLE
Manifest version 2 is deprecated, and support will be removed in 2023. See https://developer.chrome.com/blog/mv2-transition/ for more details.

### ISSUE THREAD

**Issue by jameslin1222** [fiahfy/youtube-live-chat-flow#100]
Error Messages: 

{"manifest_version":2,"icons":{"128":"icon.png"},"background":{"scripts":["background.js"]},"content_scripts":[{"run_at":"document_start","matches":["https://www.youtube.com/*"],"all_frames":false,"js":["content-script.js"],"css":["content-script.css"]},{"run_at":"document_start","matches":["https://www.youtube.com/live_chat*"],"all_frames":true,"js":["content-script-iframe.js"],"css":["content-script-iframe.css"]}],"page_action":{"default_icon":"icon.png","default_popup":"popup.html"},"options_ui":{"page":"options.html","open_in_tab":false},"permissions":["storage","https://www.youtube.com/*"],"content_security_policy":"script-src 'self' 'unsafe-eval'; object-src 'self'","name":"Flow Chat for YouTube Live","description":"Chrome Extension for Flow Chat Messages on YouTube Live","version":"0.0.51"}

How to fixed it?

**Comment by fiahfy** [comment]
This extension does not yet support manifest v3 because the package it using does not support manifest v3, but I have plan to do so before manifest v2 is no longer available.

**Comment by fiahfy** [comment]
Manifest V3 is now supported in [the latest version](https://github.com/fiahfy/youtube-live-chat-flow/releases/tag/v0.1.0).
