### ISSUE TITLE
Could not establish connection

### ISSUE THREAD

**Issue by eggplants** [fiahfy/youtube-live-chat-flow#101]
Version: 0.0.52
Chrome version: 99.0.4844.82 (Official Build) (64-bit)

![image](https://user-images.githubusercontent.com/42153744/160227566-488cc1af-85cc-4678-a29e-0d8c5319a6ad.png)

```
Uncaught (in promise) Error: Could not establish connection. Receiving end does not exist.

Context

_generated_background_page.html
```

**Comment by fiahfy** [comment]
Do not worry about this error as it does not affect the behavior.
With the [latest version](https://github.com/fiahfy/youtube-live-chat-flow/releases/tag/v0.1.0), you will not get this error.
