### ISSUE TITLE
Bottom controller is broken on old layout

### ISSUE THREAD

**Issue by Misoni64T** [fiahfy/youtube-live-chat-flow#38]
Bottom controller's layout is  broken on old YouTube layout.
![コメント 2019-05-22 150422](https://user-images.githubusercontent.com/46831731/58150865-ee88ce00-7ca2-11e9-9fcb-a43bea25eb21.png)

**Comment by fiahfy** [comment]
There are no plans to support the old layout.
If you need, adjust your own CSS with a chrome extension like stylus.

**Comment by Misoni64T** [comment]
OK. Thanks for your reply :)
