### ISSUE TITLE
font size

### ISSUE THREAD

**Issue by wilson9801** [fiahfy/youtube-live-chat-flow#48]
need to change the font size

**Comment by fiahfy** [comment]
The font size is implemented to change in proportion to the height of the video.
If you want to change the ratio between video height and font size, try changing `Height` on the `MESSAGE` tab.

**Comment by fiahfy** [comment]
Resolved [v0.0.35](https://github.com/fiahfy/youtube-live-chat-flow/releases/tag/v0.0.35)
