### ISSUE TITLE
Add commenters names

### ISSUE THREAD

**Issue by D1mon** [fiahfy/youtube-live-chat-flow#53]
It is very necessary to see who wrote the message. And now you can see only the message itself, but not who wrote it.

**Comment by fiahfy** [comment]
If the message style is changed from `Simple` to `2 lines`, author is displayed.
Is that not enough?

**Comment by D1mon** [comment]
For some, the video works for others, it does not work. Here is the link where it doesn’t work: https://youtu.be/SW6CAK1D7aY?t=216

**Comment by D1mon** [comment]
changed the height of the video (Video Height) and the names began to appear

**Comment by D1mon** [comment]
But showing in two lines does not look very nice. Can I make it appear on one line?
Example:
author: message

**Comment by fiahfy** [comment]
Consider in #54
