### ISSUE TITLE
コメントを流すタイミングを調節する機能の追加

### ISSUE THREAD

**Issue by oldman64** [fiahfy/youtube-live-chat-flow#68]
ライブ配信で通信不良などの不具合があると、
その配信のアーカイブにてチャットのタイミングがずれる場合があるので
コメントを流すタイミングを簡易的に調節する機能の追加を望みます

**Comment by fiahfy** [comment]
ライブ配信でDVRを無効にしている配信の場合、ラグが発生しても強制的に最新の映像が流れるように調整されますが、
DVRを有効にしている配信の場合、意図的にシークバーをずらした時やラグでずれた場合に映像とコメントがずれることがありますがこれを調整する機能ということでよろしいでしょうか？

参考: [ライブ配信で DVR を有効にする](https://support.google.com/youtube/answer/9296823?hl=ja)

**Comment by oldman64** [comment]
通信不良などで配信が中断された場合、リアルタイムで見ているときは問題ないのですが
後でアーカイブを確認してみると実際の放送時のコメントの日本標準時のタイムスタンプと「中断された空白の時間」の時差がコメントのズレになるときがあります。
これを何とかしてほしいと思っています。わかりにくい話で申し訳ございません。

**Comment by fiahfy** [comment]
単純にディレイを設ける(コメント側を遅らせる)ことは可能かと思いますが、差し支えなければ発生している動画URLをいただけますか？

**Comment by oldman64** [comment]
https://youtu.be/E02Dd-LBl8I
この動画は少しわかりにくいですが、途中からコメントが先行して
動画の内容と流れてるコメントの内容が食い違っていたりします
もっとわかりやすくコメントがずれている動画も過去にいくつか見ました

コメント側を遅らせるので対処は問題ないと思います。
どうか、よろしければお願いいたします

**Comment by fiahfy** [comment]
[v0.0.36](https://github.com/fiahfy/youtube-live-chat-flow/releases)
とりあえずオプションに設定を設けたので
`Behavior` -> `Delay Time` からディレイを設定してください

**Comment by oldman64** [comment]
thankyou!
