### ISSUE TITLE
ver0.0.35以降のバージョンで、Visibilityの非表示が反映されない

### ISSUE THREAD

**Issue by AcerolaJelly** [fiahfy/youtube-live-chat-flow#69]
こんばんは。
ver0.0.34までは問題ないのですが、ver0.0.35以降から
Visibilityの項目(Super Chat、Super Sticker、Membership)の表示をOFFに設定しても、再度オプションを開きなおすとONの状態に戻ってしまいます。
この件について、ご確認いただけないでしょうか？

**Comment by fiahfy** [comment]
バグっぽいので修正します
