### ISSUE TITLE
プラグインが動作しない

### ISSUE THREAD

**Issue by Panekitter** [fiahfy/youtube-live-chat-flow#70]
ChromeやVivaldi上で試してもプラグインがまったく動作しなくなったのは、自分以外にも起こっている問題でしょうか？

**Comment by fiahfy** [comment]
- 利用しているバージョンはいくつでしょうか?
- エラーが出て動作していない場合、拡張機能ページ `chrome://extensions/` に `詳細`, `削除` と並んで `エラー` ボタンが表示されているのでそのページの内容を貼っていただけると助かります

以下のことも試してみてください
- 最新バージョンを利用する
- 設定を全てデフォルトに戻す
- 拡張機能を一度削除してインストールし直す
- この拡張機能以外の拡張機能を一時的に全て無効にして試す
    - 他の拡張機能と干渉している可能性があるため
- `シークレット モードでの実行を許可する` を有効にして、シークレットウィンドウでかつYouTube にログインせずに試す
    - ログインユーザ毎にYouTube側がページの出し分けをしている可能性があるため

**Comment by Panekitter** [comment]
返信ありがとうございます。
言った通りに試してみたところ、アカウントが原因でした。
ログアウトした状態、また他のアカウントでログインした状態では動作しました。
また同じアカウントでも、新しく作成したチャンネルでログインすると動作しました。（http://urx.blue/0iGB　この機能です。）

プラグインのバージョンはv0.0.40とv0.0.39を試しました。
ブラウザはChromeの最新バージョン（83.0.4103.61）とVivaldiの最新バージョン（3.0.1874.38）。
Chromeは通常モードとシークレットモード両方試しました。
どの組み合わせでも結果は同じでした。

またTampermonkeyのプラグインFlow YouTube ChatをChromeの通常モードとシークレットモードで試しましたが、以上と同じ挙動をしました。
参考になれば幸いです。

**Comment by fiahfy** [comment]
ありがとうございます
エラーが出てないとなると、おそらくですがアカウントの状態によってチャット一覧のDOMが違っていそうですね
入会しているチャンネルの動画とそれ以外の動画で動作に違いはありますか？
ライブ配信動画とアーカイブ動画で動作に違いはありますか？
既存のアカウントと新規アカウントで設定等の違いはありますか？（課金状態やチャンネル設定、その他のYouTube設定）

**Comment by Panekitter** [comment]
入会しているチャンネル動画もそれ以外の動画も動作に違いはありませんでした。
ライブ配信動画とアーカイブ動画でも動作は同じでした。

既存のアカウントのプラグインが動作しないチャンネルは、収益化されています。また15分の制限時間を超える動画がアップロードできるようになっています。
既存のアカウントのプログインが動作する新規チャンネルと新規アカウントは、収益化も制限時間以上の動画も無効になっています。

YouTube設定はどれも同じでした。
課金はどのアカウントでもしていません。

**Comment by fiahfy** [comment]
得られている情報からすると収益化済みのアカウントのみ動作していないように見えますね
自分の保有しているアカウントだと再現がしないのでなかなか対応が難しいです

追加で確認なのですが動作しないアカウントにおいて
- チャット欄の入力フォームを移動する機能がありますがこちらは機能しますでしょうか?
- チャット欄にコメントが流れ始めたら `その他のツール` > `デベロッパーツール` で Console を開いて以下の値を確認していただけますでしょうか?
```
document.querySelector('#chatframe').contentDocument.querySelector('#items.yt-live-chat-item-list-renderer');
```
```
document.querySelector('#chatframe').contentDocument.querySelector('yt-live-chat-text-message-renderer');
```
```
document.querySelector('#chatframe').contentDocument.querySelector('yt-live-chat-text-message-renderer').parentElement;
```

**Comment by Panekitter** [comment]
入力フォームを移動する機能はオンにしても動作してないです。
Consoleの画像です。
https://i.gyazo.com/63dcbb7eee879e8ef504c599ec9eed10.png

一応こちらは動作するアカウントのConsoleです。
https://i.gyazo.com/624161f0e1780e4ba66fd746c38c82d6.png

**Comment by fiahfy** [comment]
ありがとうございます、チャット一覧のiframeの構造が大分違っていそうですね
見た目上は動作するアカウントと違いはない感じでしょうか?
追加で以下をご確認頂ければありがたいです
```
document.querySelectorAll('iframe')
```
```
Array.from(document.querySelectorAll('iframe')).map((e) => e.getAttribute('src'))
```
```
Array.from(document.querySelectorAll('iframe')).map((e) => e.contentDocument.querySelector('#items.yt-live-chat-item-list-renderer'))
```
```
Array.from(document.querySelectorAll('iframe')).map((e) => e.contentDocument.querySelector('yt-live-chat-text-message-renderer'))
```
```
Array.from(document.querySelectorAll('iframe')).map((e) => e.contentDocument.querySelector('yt-live-chat-text-message-renderer')?.parentElement)
```

**Comment by Panekitter** [comment]
動作しないアカウントの見た目です。
https://gyazo.com/0b80c91b55125e1a7d72ecea3ae7cff3

動作するアカウントの見た目です。
https://gyazo.com/1d0d5f2151a882e84d297df797dc4d70

プラグインのコメントの表示非表示をトグルするボタンが無いのと、ChromeUIの右上のプラグインの色が灰色のままになっている以外は同じだと思います。

動作しないアカウントのConsoleです。
https://gyazo.com/9c16e13981f57d6fbdce6f1e8b6dc1bc

動作するアカウントのConsoleです。
https://gyazo.com/d07a9d6b63c3ea187169835a2d4be820

**Comment by fiahfy** [comment]
ありがとうございます、スクリプトの結果を見るとチャット欄の構造が根本的に変わっている様です
アカウントやロケールを色々変えて確認してみましたが該当の状態にならず、動作確認環境が無い状態で修正を行うことは非常に難しいため、このチャットの仕様変更が一般アカウントや未ログインユーザに反映された後に対応とさせてください
何度も確認をお願いしてしまい申し訳ありませんがよろしくお願いします

**Comment by Panekitter** [comment]
了解しました。力になれず申し訳ないです。
ご対応ありがとうございました。
