### ISSUE TITLE
Not compatible with YouTube Live 360/VR?

### ISSUE THREAD

**Issue by eggplants** [fiahfy/youtube-live-chat-flow#72]
Comments will not appear on YouTube Live 360/VR. Do you have any plans to address this issue in the future?
(ex: https://www.youtube.com/watch?v=Lubz7vafWYw)

**Comment by fiahfy** [comment]
Thank you for your requests.
This issue has been fixed in [v0.41.0](https://github.com/fiahfy/youtube-live-chat-flow/releases/tag/v0.0.41).
