### ISSUE TITLE
コメントのカクつきが頻発する

### ISSUE THREAD

**Issue by AcerolaJelly** [fiahfy/youtube-live-chat-flow#76]
こんばんは。以前から、コメントがガクッ･･･ガクッ･･･と一瞬止まってしまったり、
30~40fpsで動いているような挙動になってしまうことが多く、諸々手を尽くしても改善の兆しが見えません(下記詳細)。
PCのスペックは十分あっても、仕様上ある程度のカクつきは発生してしまうものなのでしょうか？
もし有効な対処法があればご教授いただけると幸いです。

試したこと：
Chromeの再インストール
他の拡張機能の削除
常駐ソフトを減らす
RAM DISKの設定
PCのクリーンインストール

**Comment by fiahfy** [comment]
コメントのアニメーションはなるべく最適化をしているのですが、どちらかというとチャット内のコメント欄の更新でCPUが使われてしまっていてfpsが落ってしまっているようです
そのためコメント更新の少ないLiveや動画であればカクツキは少ないかと思われます
オプションの `Max Displays` でコメント数を減らすと多少は改善されるかもしれません（コメント更新頻度によってはあんまり変わらないかも）

**Comment by AcerolaJelly** [comment]
返信ありがとうございます！試してみます。
