### ISSUE TITLE
Can't send comments continuously when the screen width is narrow

### ISSUE THREAD

**Issue by eggplants** [fiahfy/youtube-live-chat-flow#77]
I'm very thankful for the useful comment form below seek bar.

When I have the screen width set to half (620px/1240px), once I submit a comment, I'm unable to submit it again, even if I re-enter. (See below.)

In `v0.0.45`: 

![Screenshot from 2020-09-01 23-45-25](https://user-images.githubusercontent.com/42153744/91866347-623ec680-ecad-11ea-8f91-8dc891bd36e7.png)

After I post a comment:

![Screenshot from 2020-09-01 23-47-26](https://user-images.githubusercontent.com/42153744/91866600-a7fb8f00-ecad-11ea-9ba1-8830f0d4f8a8.png)

Please fix... Thank you for your great work!

**Comment by fiahfy** [comment]
I'm trying to reproduce it.
I confirmed that there is no problem if the Live is not set to slow mode.
I'm not sure if it works, but try enabling `Grow Bottom Chat Input`.

**Comment by eggplants** [comment]
Yes. I have just confirmed `Grow Bottom Chat Input` feature is worked well even if making window width is half on my environment. Thanks!
