### ISSUE TITLE
Any chance to port it to Firefox?

### ISSUE THREAD

**Issue by usadapekora9** [fiahfy/youtube-live-chat-flow#78]
It worked perfectly in chrome, thank you very much! 

But I'm a FF user(because it used less resources' cpu/ram even with 20+ tabs) 

I'm not sure how hard it is to covert .crx into FF addon but I still want to suggest it.

**Comment by fiahfy** [comment]
It's not the best way, but It is available as Temporary Add-on in Firefox.
https://extensionworkshop.com/documentation/develop/temporary-installation-in-firefox/

**Comment by usadapekora9** [comment]
> 
> 
> It's not the best way, but It is available as Temporary Add-on in Firefox.
> https://extensionworkshop.com/documentation/develop/temporary-installation-in-firefox/

Ohhhhh!!! It worked!! 
Thanks a lot~

PS: Though I need to edit the option in notepad (It's not really a problem)
