### ISSUE TITLE
ブランドアカウント元で動作しない報告

### ISSUE THREAD

**Issue by Sp140** [fiahfy/youtube-live-chat-flow#79]
こんにちは。
プラグインが動作せずに困っていたところ、ある1つのアカウントで動作していないことが確認できました。
issues closedの＃70を見ていて気が付きました。
そのアカウントは動画投稿や収益化、課金等は行っていませんが、
サブアカウント用にブランドアカウントは2つ作成しておりました。
作成した2つのブランドアカウントでの動作は確認できており、
元々あったアカウントの方でのみ動作しませんでした。
また、ログアウトした状態やメールアドレスの違う、ブランドアカウントを
作成していない別のアカウントではちゃんと動作することが確認できました。
v0.0.45、v0.0.43にて動作しませんでした。
別の原因があるかもしれませんが、私が考えられるものはブランドアカウント
が原因であると感じております。
確認お願いします。

**Comment by fiahfy** [comment]
以下の様にブランドアカウントを2つ作成したアカウントで、アカウントを切り替えて動作を確認したところ、3つ全てのアカウントで正常に動作することを確認しました
別の要因がありそうですね
```
メインアカウント
 + ブランドアカウント1
 + ブランドアカウント2
```

**Comment by Sp140** [comment]
検証ありがとうございます。
なるほど、ブランドアカウントでも動作しましたか…
他には心当たりはないですね…お役に立てずすみません。
