### ISSUE TITLE
 Comments shift to the top

### ISSUE THREAD

**Issue by fukaki** [fiahfy/youtube-live-chat-flow#80]
After version 0.0.44, The comments displayed on
the 2nd and subsequent lines will shift to the top.
Is this a specification?

**Comment by fiahfy** [comment]
That's not a specification.
Can you post a screenshot if you don't mind?

You may also try the following
- Reinstalling the extension
- Update to the latest version of Chrome
- Log out and check the behavior

**Comment by fukaki** [comment]
When the flow messeges button is displayed in black
The message goes up to the top. This doesn't happen every time
But it doesn't happen at 0.0.43. I don't know how to reproduce it.

![10](https://user-images.githubusercontent.com/28802856/96960683-f440ae00-153d-11eb-9a5c-f5d1d9994490.jpg)

**Comment by fiahfy** [comment]
Does this happen on Chrome? 
We do not guarantee that it will work on Brave.

**Comment by fukaki** [comment]
This problem doesn't occur with chrome. However
I like Brave (Chromium) which eliminates ads without extensions
so I'm going to use 0.0.43. Thanx!
