### ISSUE TITLE
Bug?: Move from premiere public video to chat disabled video

### ISSUE THREAD

**Issue by eggplants** [fiahfy/youtube-live-chat-flow#82]
## Note

This buggy behavior could be a problem with YouTube's system.

## Reproduction method

- Play: <https://www.youtube.com/watch?v=HKbGL0eqy0c>
  - Click `チャットのリプレイを表示する`
- Then, play: <https://www.youtube.com/watch?v=LRaAff4LF7Q> from notification menu
- Another player appear above `この動画ではチャットのリプレイを利用できません。`

## Screenshot

![image](https://user-images.githubusercontent.com/42153744/97980358-fc3cff80-1e13-11eb-8a17-bb211cb279a5.png)

**Comment by fiahfy** [comment]
I tried to reproduce the same as above with the extension disabled, but it reproduced the same way.
Therefore, I don't think this phenomenon is due to the extension.
