### ISSUE TITLE
Set input form to `disabled` when posting comment is disabled on slow mode

### ISSUE THREAD

**Issue by eggplants** [fiahfy/youtube-live-chat-flow#86]
In a live stream with  [Slow mode](https://support.google.com/youtube/answer/9826490#zippy=%2Cslow-mode) set, I would like this tool to set input form to `disabled` attribute when posting my comment is disabled and I am waiting for re-postable.

**Comment by fiahfy** [comment]
I think it is better not to set it to disabled, because there are cases where you may want to pre-input even if you cannot comment.

**Comment by eggplants** [comment]
Indeed... Thank you for your response!

**Comment by eggplants** [comment]
So, for example, could you put a message on the form? (like: "unable to submit")
