### ISSUE TITLE
ブロック時の不具合

### ISSUE THREAD

**Issue by fukaki** [fiahfy/youtube-live-chat-flow#88]
ブロックやキャンセルを押しても、このユーザーをブロックしますか？
という表示が残って、チャット欄が小さいままなのは私だけでしょうか
![iX2L82bAuB0GYyK1616073378_1616073426 0  (2)](https://user-images.githubusercontent.com/28802856/111639149-50ce9d80-883e-11eb-887a-d01812c76aeb.jpg)

**Comment by fiahfy** [comment]
こちら再現ができませんでした、この拡張機能を無効にした状態でも発生するかどうかご確認ください

**Comment by fukaki** [comment]
どうやら私の環境だけのようですね。0.0.47を使ってみます
ありがとう御座いました
