### ISSUE TITLE
[Bug] Messages aren't written correctly and won't send

### ISSUE THREAD

**Issue by jogerj** [fiahfy/youtube-live-chat-flow#90]
![image](https://user-images.githubusercontent.com/30559735/111937433-03656100-8ac8-11eb-9d0b-6485b8f5307e.png)
![image](https://user-images.githubusercontent.com/30559735/111937925-22182780-8ac9-11eb-84f3-1fa8890b8193.png)

Easier to explain how to reproduce than describing it:
1. if you type something in the text field, sometimes the "Say something..." doesn't disappear, but pressing 'enter' or clicking send button does not send the message.
2. sometimes it updates and fixes itself. Once "Say something..." disappears, the message can be sent.
3. It doesn't seem to matter whether slow mode is activated or not.

version 0.0.47 on Chrome 89.0.4389.90 (Official Build) (64-bit)

**Comment by fiahfy** [comment]
I was not able to reproduce this.
Please check if the problem is resolved by refreshing the page, and if not, how often it occurs.
Also, please check if the problem still occurs with all other extensions disabled.

**Comment by jogerj** [comment]
Solved.

It appears the problem was caused by another extension I have installed ([Ruffle](https://github.com/ruffle-rs/ruffle)).
