### ISSUE TITLE
動画上に流すチャットに適用するフォントの変更

### ISSUE THREAD

**Issue by Moromi-jagiism** [fiahfy/youtube-live-chat-flow#98]
自身のパソコンにインストールしているフォントを使用し、
画面上に流すYoutubeLiveのチャットに適用するフォントを変更したいです。

**Comment by fiahfy** [comment]
`Extended Style` に `font-family` を設定してみてください

e.g.
```
font-family: 'YuGothic';
```

https://w3g.jp/sample/css/font-family

**Comment by Moromi-jagiism** [comment]
解決しました。
対応してくださりありがとうございます。
